import { GridColDef, GridValueGetterParams } from "@mui/x-data-grid";

export const columns: GridColDef[] = [
  {
    field: "month",
    headerName: "Month",
    width: 90,
  },
  {
    field: "food",
    headerName: "Food",
    type: "number",
    width: 90,
    editable: true,
  },
  {
    field: "accomandation",
    headerName: "Accomandation",
    type: "number",
    width: 120,
    editable: true,
  },
  {
    field: "entertainment",
    headerName: "Entertainment",
    type: "number",
    width: 120,
    editable: true,
  },
  {
    field: "transport",
    headerName: "Transport",
    type: "number",
    width: 120,
    editable: true,
  },
  {
    field: "shopping",
    headerName: "Shopping",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "other",
    headerName: "Other",
    type: "number",
    width: 120,
    editable: true,
  },
  {
    field: "total",
    headerName: "Total exp",
    description: "This column has a value getter and is not sortable.",
    sortable: false,
    width: 120,
    valueGetter: (params: GridValueGetterParams) => {
      return (
        params.row.food +
        params.row.accomandation +
        params.row.entertainment +
        params.row.transport +
        params.row.shopping +
        params.row.other
      );
    },
  },
];

export const rows = [
  {
    id: 1,
    month: "Januar",
    food: 1500,
    accomandation: 2100,
    entertainment: 535,
    transport: 250,
    shopping: 200,
    other: 200,
  },
  {
    id: 2,
    month: "Februar",
    food: 1500,
    accomandation: 2100,
    entertainment: 535,
    transport: 250,
    shopping: 200,
    other: 200,
  },
  {
    id: 3,
    month: "March",
    food: 1500,
    accomandation: 2100,
    entertainment: 535,
    transport: 250,
    shopping: 200,
    other: 200,
  },
  {
    id: 4,
    month: "April",
    food: 1500,
    accomandation: 2100,
    entertainment: 535,
    transport: 250,
    shopping: 200,
    other: 200,
  },
  {
    id: 5,
    month: "May",
    food: 1500,
    accomandation: 2100,
    entertainment: 535,
    transport: 250,
    shopping: 200,
    other: 200,
  },
  {
    id: 6,
    month: "June",
    food: 1500,
    accomandation: 2100,
    entertainment: 535,
    transport: 250,
    shopping: 200,
    other: 200,
  },
  {
    id: 7,
    month: "July",
    food: 1500,
    accomandation: 2100,
    entertainment: 535,
    transport: 250,
    shopping: 200,
    other: 200,
  },
  {
    id: 8,
    month: "August",
    food: 1500,
    accomandation: 2100,
    entertainment: 535,
    transport: 250,
    shopping: 200,
    other: 200,
  },
  {
    id: 9,
    month: "September",
    food: 1500,
    accomandation: 2100,
    entertainment: 535,
    transport: 250,
    shopping: 200,
    other: 200,
  },
  {
    id: 10,
    month: "October",
    food: 1500,
    accomandation: 2100,
    entertainment: 535,
    transport: 250,
    shopping: 200,
    other: 200,
  },
  {
    id: 11,
    month: "November",
    food: 1500,
    accomandation: 2100,
    entertainment: 535,
    transport: 250,
    shopping: 200,
    other: 200,
  },
  {
    id: 12,
    month: "December",
    food: 1500,
    accomandation: 2100,
    entertainment: 535,
    transport: 250,
    shopping: 200,
    other: 200,
  },
];
